name: rawtherapee
base: core22
version: "5.10"
grade: stable
summary: cross-platform raw image processing program
description: |
  RawTherapee is a powerful, cross-platform raw photo
  processing program, released as libre software under
  the GNU General Public License Version 3. It is written
  mostly in C++ using a GTK+ front-end. It uses a patched
  version of dcraw for reading raw files, with an in-house
  solution which adds the highest quality support for certain
  camera models unsupported by dcraw and enhances the accuracy
  of certain raw files already supported by dcraw.
  It is notable for the advanced control it gives
  the user over the demosaicing and development process.

confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  rawtherapee:
    command: usr/bin/rawtherapee
    common-id: com.rawtherapee.RawTherapee
    command-chain:
      - snap/command-chain/desktop-launch
    extensions:
      - gnome
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - unity7
      - wayland
      - x11
      - removable-media
      - home
      - opengl
      - mount-observe
      - removable-media

layout:
  /usr/share/rawtherapee:
    symlink: $SNAP/usr/share/rawtherapee

lint:
  ignore:
    - library:
      - usr/lib/**/libcolordprivate*
      - usr/lib/**/libdconf*
      - usr/lib/**/libfftw3f_threads*
      - usr/lib/**/libglibmm_generate_extra_defs*
      - usr/lib/**/libicuio*
      - usr/lib/**/libicutest*
      - usr/lib/**/libicutu*
      - usr/lib/**/libicui18n*
      - usr/lib/**/libappindicator*
      - usr/lib/**/libgdk_pixbuf_xlib*
      - usr/lib/**/libdbusmenu-gtk*
      - usr/lib/**/libdbusmenu-glib*

parts:

  build-rawtherapee:
    source: https://github.com/Beep6581/RawTherapee
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX="/usr"
      - -DBINARY_PACKAGE_BUILD=ON
      - -DCMAKE_SYSTEM_PREFIX_PATH="${CRAFT_STAGE}"
    parse-info:
      - usr/share/metainfo/org.rawrherapee.rawrherapee.appdata.xml
    build-packages:
      - pkg-config
      - curl
      - wget
      - libbz2-dev
      - libpulse0
      - libcanberra-gtk3-dev
      - libexiv2-dev
      - libexpat1-dev
      - libfftw3-dev
      - libglibmm-2.4-dev
      - libgtk-3-dev
      - libgtkmm-3.0-dev
      - libiptcdata0-dev
      - libjpeg8-dev
      - liblcms2-dev
      - libpng-dev
      - libsigc++-2.0-dev
      - libtiff5-dev
      - zlib1g-dev
      - liblensfun-dev
      - librsvg2-dev
    stage-packages:
      - libatk-bridge2.0-0
      - libatkmm-1.6-1v5
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairomm-1.0-1v5
      - libcanberra-gtk3-0
      - libcanberra0
      - libepoxy0
      - libexiv2-27
      - libfftw3-single3
      - libgtk-3-0
      - libgtkmm-3.0-1v5
      - libglibmm-2.4-1v5
      - libgomp1
      - liblcms2-2
      - liblensfun1
      - libltdl7
      - libogg0
      - libpangomm-1.4-1v5
      - librsvg2-2
      - libsigc++-2.0-0v5
      - libtdb1
      - libvorbis0a
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libpulse0
